### ISSUE TITLE
One Time Expenses being double counted when calculating "Estimated Income, Drawdowns, and Debt"

### ISSUE THREAD

**Issue by ngupta23** [newretirement/fpe-api#3]
When I enter a one-time expense in the future, under the Insights --> "Income and Expenses" tab, "Estimated Expenses" is calculated correctly, but the "Estimated Income, Drawdowns, and Debt" section adds this one-time expense amount twice, resulting in more amount being drawn down from accounts than is necessary.

Can this be fixed?

PS: I am using the web version of the tool, not the API, but the issue may be related.

**Comment by cet001** [comment]
Thanks for your feedback.  There are some known charting UI/UX issues within the consumer app, which are being addressed.  However, we believe the issue you are observing is not being caused by the FPE financial service, so marking this specific issue as closed.
